### ISSUE TITLE
botname archive

### ISSUE THREAD

**Issue by digcat** [ntmcminn/slackbot-alfresco#2]
hi, just testing your excellent slack bot.  have got @botname search working fine, but having issues with the @botname archive, here is the conversation, 

daren [1:28 PM]  
@buzzdocs archive

buzzdocsBOT [1:28 PM]  
OK, I can do that.  How much would you like to archive (x minutes, hours, days, messages)?

daren [1:28 PM]  
30 minutes

buzzdocsBOT [1:28 PM]  
What should I call the archive (default: `23-9-2016-1477189681410-archive.txt`)?

daren [1:28 PM]  
beecon

buzzdocsBOT [1:28 PM]  
You want me to archive 30 minutes of this chat, and name it `beecon.txt`?

daren [1:28 PM]  
yes

buzzdocsBOT [1:28 PM]  
OK! I will create that archive for you

new messages
[1:28]  
No messages met your search criteria.  Are you sure you asked me for something I can find?

**Comment by ntmcminn** [comment]
This is correct.  For some reason I can't get the date range APIs in Slack to work correctly.  Right now only message count archiving is working.  If you figure it out, I'd love a pull request :-)
